version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    container_name: climind-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - climinddb:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  climinddb:
